<?xml version="1.0" encoding="utf-8"?><Database Name="MyDatabase" Class="UsersDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\MyDatabase.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MyDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="ID_user" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fio_user" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="login_user" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="age_user" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="phone_user" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="foto_user" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>